### ISSUE TITLE
Open Query Runner is not working

### ISSUE THREAD

**Issue by raulgenially** [butchland/vscode-dbt-bigquery-power-user#1]
A System Error appear:

![image](https://user-images.githubusercontent.com/73470842/159521697-218b050e-7c61-4a8e-bf6e-e6aee4abf4c4.png)

**Comment by butchland** [comment]
Thanks for posting this. I've only really used the extension via WSL so if at all possible, that might be a possible workaround. I'll work on this and publish an update soon.

**Comment by butchland** [comment]
@raulgenially Please upgrade to version 0.5.18 and see if this fixes your problem.

**Comment by raulgenially** [comment]
@butchland Now all works fine!!! Great job

**Comment by raulgenially** [comment]
Hi @butchland ,

Everything seems to go wrong again :(
![image](https://user-images.githubusercontent.com/73470842/168749862-93749965-828b-4ee9-89db-4f07c35c616c.png)

**Comment by butchland** [comment]
Ok. Willl check

**Comment by butchland** [comment]
Reverted last change.  @raulgenially please upgrade to 0.5.22

**Comment by raulgenially** [comment]
Upgraded, but still the same :( 
![image](https://user-images.githubusercontent.com/73470842/168823443-6bbcfc71-4b7b-4b4b-954f-7734ec08e5d0.png)

**Comment by butchland** [comment]
Weird. Ok will investigate this further. Thanks for your patience.

**Comment by b0lle** [comment]
+1 while using windows. Seems like the path will is not transformed to windows path.
For example:
"this\is\bobbys\path" transforms to "this\isobbys\path"

**Comment by butchland** [comment]
hi @b0lle @raulgenially try upgrading to version 0.5.23. 
Thanks for the feedback!

**Comment by raulgenially** [comment]
Still the same @butchland :(

Could you double-check @b0lle ?

**Comment by b0lle** [comment]
Its still not working. Seems that the transformation (see my post above) is now correct. But the path now begins with `/c:/...`. I think the path should not begin with a slash (`c:/...` would be correct)

**Comment by Gregory108** [comment]
Alternative solution: make use of BigQuery Runner plugin (minodisk.bigquery-runner)? It seems to be updated this year
