### ISSUE TITLE
When running dbt QueryRunner it opens blank section in the middle

### ISSUE THREAD

**Issue by jirigrill** [butchland/vscode-dbt-bigquery-power-user#2]
Hi,
first thank you for this extension, it is life saver! But when I am running QueryRunner it screates in VSC blank section in the middle as marked on a screenshot.

![Screenshot 2022-08-08 at 14 38 33](https://user-images.githubusercontent.com/12986457/183420497-d02d720a-ef15-44f0-a6b7-9f987f4af636.png)

Do I have it wrongly setup or is it bug of this extension? Thank you!

**Comment by butchland** [comment]
Yes this is a known issue -- its not exactly a bug, more on a limitation of how vscode windows can be opened in relation to the editor window.
