### ISSUE TITLE
sql runner could not load default credentials

### ISSUE THREAD

**Issue by wei-kortx** [butchland/vscode-dbt-bigquery-power-user#3]
is there a step to set up bq credentials for the sql runner? 
![Screen Shot 2022-09-01 at 2 20 11 PM](https://user-images.githubusercontent.com/38010670/187985432-6307430c-87e2-4db6-bf25-45cdd4ecea02.png)

**Comment by butchland** [comment]
Try specifying the big query credentials in your vscode settings (`settings.json`) like so:
```
    "dbt.bigquery.keyFilename": "<path-to-your/service-account.json>",
    "dbt.bigquery.projectId": "<your-google-bigquery-project-name>",
```
Make sure you use the correct path separators for linux (`/`) and/or windows `\\`).
